### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by andyRon** [lanbing510/DouBanSpider#6]
Python 新手
- 爬完保存数据时出问题
  
  ```
  Traceback (most recent call last):
    File "doubansider.py", line 142, in <module>
      print_book_lists_excel(book_lists,book_tag_lists)
    File "doubansider.py", line 110, in print_book_lists_excel
      wb=Workbook(optimized_write=True)
  TypeError: __init__() got an unexpected keyword argument 'optimized_write'
  ```
- 然后我去掉参数`optimized_write`， 又报另外的错误
  
  ```
  Traceback (most recent call last):
    File "doubansider.py", line 143, in <module>
      print_book_lists_excel(book_lists,book_tag_lists)
    File "doubansider.py", line 119, in print_book_lists_excel
      ws[i].append([count,bl[0],float(bl[1]),int(bl[2]),bl[3],bl[4]])
  UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-2: invalid decimal Unicode string
  ```
- 是否可以爬一段数据就保存到excel中，一直放在内存中对性能没有影响吗？

**Comment by lanbing510** [comment]
这里的代码是老版本的，豆瓣进行了很多更新，已经不再适用。
